#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
V2 Batch52 long conversation end-to-end regression.

Purpose:
- Validate 12+ turns continuous conversation.
- Validate context inheritance, bulk execution, follow-up analysis and rolling context.
- Validate no unexpected fallback to V1 for context-following questions.

Safety:
- Executes one confirmed batch of read-only commands only after YES.
- Commands are generated by V2 and must pass CLI guard.
"""

from __future__ import print_function

import json
import sys
import urllib.parse
import urllib.request
from datetime import datetime


BASE_URL = "http://127.0.0.1:18081"


def http_json(method, path, payload=None, timeout=360):
    data = None
    headers = {"Accept": "application/json"}

    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"

    req = urllib.request.Request(
        BASE_URL + path,
        data=data,
        headers=headers,
        method=method,
    )

    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8", errors="replace"))


def chat(question, conversation_id=None, timeout=360):
    payload = {
        "question": question,
        "user": "baoleiji",
        "limit": 20,
        "planner_mode": "llm",
        "debug": False,
    }
    if conversation_id:
        payload["conversation_id"] = conversation_id

    return http_json("POST", "/api/v1/chat", payload=payload, timeout=timeout)


def get_context(conversation_id):
    query = urllib.parse.urlencode({"conversation_id": conversation_id})
    return http_json("GET", "/api/v1/v2/context?" + query, timeout=120)


def require(condition, message, errors):
    if condition:
        print("[OK]", message)
    else:
        print("[FAIL]", message)
        errors.append(message)


def compact_response(data):
    return {
        "status": data.get("status"),
        "planner_source": data.get("planner_source"),
        "conversation_id": data.get("conversation_id"),
        "parsed": data.get("parsed"),
        "answer": data.get("answer"),
        "count": data.get("count"),
        "returned": data.get("returned"),
        "items": data.get("items"),
        "v2_keys": sorted(list((data.get("v2") or {}).keys())),
    }


def main():
    errors = []
    report = {
        "created_at": datetime.now().isoformat(),
        "turns": [],
        "errors": errors,
    }

    print("========== V2 Batch52 Long Conversation Regression ==========")

    conv_id = None

    cases = [
        {
            "name": "seed_cpu",
            "question": "WG88-SW-H15-1当前CPU利用率异常，给我第一批排查命令",
            "expect_source": "v2_chat_router",
            "expect_status": "ok",
            "expect_intent": "cpu_check",
            "must_contain": ["Prometheus 当前 CPU 证据"],
            "timeout": 180,
        },
        {
            "name": "context_execute_without_yes",
            "question": "将你上述给出的命令在设备上执行，然后根据命令的结果给出分析",
            "expect_source": "v2_execution_confirmation",
            "expect_status": "pending_confirmation",
            "must_contain": ["确认执行全部命令 YES"],
            "timeout": 180,
        },
        {
            "name": "bulk_execute_yes",
            "question": "确认执行全部命令 YES",
            "expect_source": "v2_execution_confirmation",
            "expect_status_in": ["ok", "partial"],
            "must_contain": ["综合分析", "命令执行结果摘要", "建议下一步"],
            "timeout": 360,
            "must_execute": True,
        },
        {
            "name": "followup_conclusion",
            "question": "结合以上三点，给出更准确的结论，当前是否真的是CPU问题？",
            "expect_source": "v2_followup_analysis",
            "expect_status": "ok",
            "must_contain": ["我会沿用上一轮 V2 会话上下文继续分析", "综合结论", "建议下一步"],
            "timeout": 180,
        },
        {
            "name": "followup_next_steps",
            "question": "如果CPU不高，下一步应该排查什么？还需要查Prometheus历史趋势吗？",
            "expect_source": "v2_followup_analysis",
            "expect_status": "ok",
            "must_contain": ["Prometheus", "历史趋势"],
            "timeout": 180,
        },
        {
            "name": "inherited_route",
            "question": "这个设备的路由表有多少条？",
            "expect_source": "v2_chat_router",
            "expect_status": "ok",
            "expect_intent": "route_table",
            "expect_inherited": True,
            "must_contain": ["已继承上一轮 V2 上下文"],
            "timeout": 180,
        },
        {
            "name": "inherited_cpu_again",
            "question": "继续查看当前设备CPU，还需要哪些命令？",
            "expect_source": "v2_chat_router",
            "expect_status": "ok",
            "expect_intent": "cpu_check",
            "expect_inherited": True,
            "must_contain": ["已继承上一轮 V2 上下文"],
            "timeout": 180,
        },
        {
            "name": "followup_history_again",
            "question": "根据刚才结果，还需要继续看CPU历史趋势吗？",
            "expect_source": "v2_followup_analysis",
            "expect_status": "ok",
            "must_contain": ["历史趋势"],
            "timeout": 180,
        },
        {
            "name": "followup_summary",
            "question": "总结一下目前这个设备CPU排查到的结论",
            "expect_source": "v2_followup_analysis",
            "expect_status": "ok",
            "must_contain": ["综合结论", "当前设备"],
            "timeout": 180,
        },
        {
            "name": "followup_logs",
            "question": "根据刚才结果，下一步要重点看哪些日志？",
            "expect_source": "v2_followup_analysis",
            "expect_status": "ok",
            "must_contain": ["日志"],
            "timeout": 180,
        },
        {
            "name": "topic_only_continue",
            "question": "继续给我下一批排查命令",
            "expect_source": "v2_chat_router",
            "expect_status": "ok",
            "expect_inherited": True,
            "timeout": 180,
        },
        {
            "name": "final_context_followup",
            "question": "这些结果说明设备本身有问题吗？",
            "expect_source": "v2_followup_analysis",
            "expect_status": "ok",
            "must_contain": ["综合结论"],
            "timeout": 180,
        },
    ]

    for idx, case in enumerate(cases, 1):
        print("\n========== Turn {}: {} ==========".format(idx, case["name"]))
        print("QUESTION:", case["question"])

        data = chat(case["question"], conversation_id=conv_id, timeout=case.get("timeout", 180))
        if not conv_id:
            conv_id = data.get("conversation_id")

        parsed = data.get("parsed") or {}
        answer = data.get("answer") or ""
        items = data.get("items") or []

        compact = compact_response(data)
        report["turns"].append({
            "index": idx,
            "case": case["name"],
            "question": case["question"],
            "response": compact,
        })

        print(json.dumps(compact, ensure_ascii=False, indent=2)[:9000])

        require(data.get("planner_source") == case["expect_source"], "{} planner_source expected".format(case["name"]), errors)

        if "expect_status" in case:
            require(data.get("status") == case["expect_status"], "{} status expected".format(case["name"]), errors)

        if "expect_status_in" in case:
            require(data.get("status") in case["expect_status_in"], "{} status in expected list".format(case["name"]), errors)

        if case.get("expect_intent"):
            require(parsed.get("v2_intent") == case["expect_intent"], "{} v2_intent expected".format(case["name"]), errors)

        if case.get("expect_inherited") is not None:
            require(parsed.get("context_inherited") is case.get("expect_inherited"), "{} context_inherited expected".format(case["name"]), errors)
            require(parsed.get("device_name") == "WG88-SW-H15-1", "{} inherited device_name expected".format(case["name"]), errors)
            require(parsed.get("mgmt_ip") == "10.189.250.79", "{} inherited mgmt_ip expected".format(case["name"]), errors)

        for needle in case.get("must_contain", []):
            require(needle in answer, "{} answer contains {}".format(case["name"], needle), errors)

        if case.get("must_execute"):
            require(len(items) >= 4, "{} returns execution items".format(case["name"]), errors)
            ok_count = sum(1 for x in items if x.get("ok") is True)
            require(ok_count >= 4, "{} at least four commands ok".format(case["name"]), errors)

        require(data.get("planner_source") != "llm_tool_planner", "{} does not fallback to V1 planner".format(case["name"]), errors)

    print("\n========== Context Debug ==========")
    ctx = get_context(conv_id)
    ctx_data = ctx.get("context") or {}

    context_preview = {
        "exists": ctx.get("exists"),
        "conversation_id": conv_id,
        "current_device": ctx_data.get("current_device"),
        "current_topic": ctx_data.get("current_topic"),
        "current_intent": ctx_data.get("current_intent"),
        "active_focus": ctx_data.get("active_focus"),
        "context_stats": ctx_data.get("context_stats"),
        "recent_turns_count": len(ctx_data.get("recent_turns") or []),
        "last_executions_count": len(ctx_data.get("last_executions") or []),
        "has_last_followup_analysis": bool(ctx_data.get("last_followup_analysis")),
        "rolling_summary": ctx_data.get("rolling_summary"),
    }

    print(json.dumps(context_preview, ensure_ascii=False, indent=2)[:10000])
    report["context"] = context_preview

    require(ctx.get("exists") is True, "context exists", errors)
    require((ctx_data.get("current_device") or {}).get("device_name") == "WG88-SW-H15-1", "context current_device expected", errors)
    require(len(ctx_data.get("recent_turns") or []) >= 12, "context records at least 12 turns", errors)
    require(len(ctx_data.get("recent_turns") or []) <= 30, "context recent_turns within compact limit", errors)
    require(bool(ctx_data.get("rolling_summary")), "context rolling_summary exists", errors)
    require(bool(ctx_data.get("active_focus")), "context active_focus exists", errors)
    require(bool(ctx_data.get("context_stats")), "context_stats exists", errors)
    require(bool(ctx_data.get("last_followup_analysis")), "last_followup_analysis exists", errors)

    out = "/tmp/v2_long_conversation_regress_{}.json".format(datetime.now().strftime("%Y%m%d_%H%M%S"))
    with open(out, "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)

    print("\n========== Result ==========")
    print("conversation_id:", conv_id)
    print("report:", out)

    if errors:
        print("status: FAILED")
        return 1

    print("status: PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
